language: node_js
node_js:
 - "stable"
install: npm install
services:
- postgresql
env:
- DB_USERNAME=selfless_user DB_PASSWORD=null DBNAME=selfless_service_test
before_script:
- psql -c 'drop database if exists selfless_service_test;' -U postgres
- psql -c 'create database selfless_service_test;' -U postgres
- psql -c "CREATE USER selfless_user WITH PASSWORD 'null';" -U postgres

script: npm test
